[package]
name = "adder"
version = "0.1.0"
edition = "2024"

[dependencies]
# Cargo need to be explicit about the dependency relationships
add_one = { path = "../add_one" }
add_two = { path = "../add_two" }
